### ISSUE TITLE
bot1.py executing table.py gives permission error

### ISSUE THREAD

**Issue by Dathison** [Dathison/DiscordBot#7]
The following error is generated when the !table command is executed:

`Ignoring exception in command table:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/path/to/repo/DiscordBot/bot1.py", line 67, in table
    await ctx.send(str(subprocess.run("table.py")))
  File "/usr/local/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: 'table.py'`

`The above exception was the direct cause of the following exception:`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.10/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: PermissionError: [Errno 13] Permission denied: 'table.py'`

This is likely related to the error that is generated when the table.py is run on its own:
`Traceback (most recent call last):
  File "/path/to/repo/DiscordBot/table.py", line 1, in <module>
    import lxml
ModuleNotFoundError: No module named 'lxml'`

**Comment by Dathison** [comment]
This has been integrated into the main bot.py script and is no longer relevant.
